version: '3.8'

services:
  memdump_service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FILE_NAME=${FILE_NAME} # Passe la variable d'environnement à Docker
      - KERNEL_VERSION=${KERNEL_VERSION} # Si tu veux passer KERNEL_VERSION
    volumes:
      - ./start.sh:/start.sh # Monte le script start.sh
    command: [ "/bin/bash", "/start.sh" ]
    stdin_open: true
    tty: true
