version: '3.8'

services:
  memdump_service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        FILE_NAME: ${FILE_NAME}
        KERNEL_VERSION: ${KERNEL_VERSION}
    environment:
      - FILE_NAME=${FILE_NAME}
      - KERNEL_VERSION=${KERNEL_VERSION} # Passer la variable d'environnement
    volumes:
      - ./start.sh:/start.sh
    command: [ "/bin/bash", "/start.sh" ]
    stdin_open: true
    tty: true
