version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend-dump-analyzer/Dockerfile
    ports:
      - "8281:8281"
    volumes:
      - ./backend-dump-analyzer:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1

  frontend:
    build:
      context: ./frontend-dump-analyzer
      dockerfile: Dockerfile
    ports:
      - "8280:8280"
    environment:
      - REACT_APP_API_URL=http://localhost:8281
    volumes:
      - ./frontend-dump-analyzer:/app
      - /app/node_modules
    depends_on:
      - backend
